### PR TITLE
Support for GHC 8.2.1 Stackage nightly

### PR DESCRIPTION
**Pull request by varosi**
- Added future dependency of Shelly.hs, based on this pull-request https://github.com/yesodweb/Shelly.hs/pull/149

### CODE REVIEW

**Comment by cdornan** [comment]
Thanks for this @varosi -- I am very busy with other things right now but should be able to get into this next week.

**Comment by varosi** [comment]
Great! But first a pull-request in Shelly.hs should be approved, because this change depends on theirs.

**Comment by cdornan** [comment]
@varosi for sure I will check the situation of Shelly before doing anything.

(I will leave the PR open, but I have scripts for generating a new release which generate the cabal files from templates, so expect me to close this PR and apply the patch manually. This is not a problem -- just so that yiu know what is going on.)

**Comment by varosi** [comment]
hm, AppVeyor fails with:
```
gpg: keyserver communications error: key not found
gpg: keyserver communications error: bad public key
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   4  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   4  signed:   3  trust: 0-, 0q, 0n, 4m, 0f, 0u
gpg: depth: 2  valid:   3  signed:   0  trust: 3-, 0q, 0n, 0m, 0f, 0u
gpg: keyserver refresh failed: bad public key
==> ERROR: A specified local key could not be updated from a keyserver.
```

**Comment by varosi** [comment]
Is this problem with my changes?

**Comment by cdornan** [comment]
@varosi leave this with me &mdash; as I said above I am going to have to resubmit this patch anyway.

Sorry for the delay: things have got very busy and it might take me a week or two to get to this.

**Comment by varosi** [comment]
Okay! Thank you very much!

**Comment by varosi** [comment]
Hello!
Any progress here?

**Comment by varosi** [comment]
What I can help with incorporating this pull request?

**Comment by varosi** [comment]
There is still that problem:
gpg: keyserver refresh failed: bad public key

**Comment by cdornan** [comment]
Sorry @varoi &mdash; since you raised this PR I have been completely jammed, but I will make time this weekend to review everything and hopefully merge everything and cut a release.

**Comment by varosi** [comment]
Thank you!

**Comment by cdornan** [comment]
Sorted (see #161) &mdash; sorry for the delay.

**Comment by varosi** [comment]
np, thanks a lot!
На пт, 14.12.2018 г., 15:57 ч. Chris Dornan <notifications@github.com>
написа:

**Pull request closed without merging**
