### PR TITLE
Upgrading to LTS-12.1 and GHC-8.4.3 compatibility fixes

### PR DESCRIPTION
**Pull request by saurabhnanda**
Extremely hacky. Just got it to compile anyhow, for my own use-case. Let me know what needs to be fixed to get this merged.

### CODE REVIEW

**Comment by saurabhnanda** [comment]
How does one deal with stuff like this? On one LTS this is correct, on another this is incorrect.

```
C:\stack\examples\re-tests.lhs:51:1: warning: [-Wdodgy-imports]
    Module `Test.Tasty.SmallCheck' does not export `test'
<no location info>: error: 
Failing due to -Werror.
```

**Comment by Wizek** [comment]
I'm also interested in support for later GHC versions. @saurabhnanda, perhaps `#ifdef` CPP macros can be a solution? Or setting `-Wno-dodgy-imports`? Either way, I'm giving your branch a try.

**Comment by Wizek** [comment]
Potentially related pull requests: #158 and #152

**Comment by saurabhnanda** [comment]
@wizek did my PR work for you?

**Comment by cdornan** [comment]
Merging this into a new topic branch.

**Pull request merged**
