### PR TITLE
Support GHC 9.2 without warnings

### PR DESCRIPTION
**Pull request by vdukhovni**
Given that the project .cabal file uses -Wall -Werror, all warnings must be
addressed.

   * GHC 9.2 warns about missing explicit `liftTyped`: use DeriveLift
     available with GHC 8.0 or later
   * The time-1.5 library has `parseTimeM` and no `parseTime`. The
     latter is simply `parseTimeM True`.
   * GHC 9.2 demands `FlexibleContexts` in Match.lhs and Matches.lhs
   * Suppress warning about unused wildcard record fields, by using
     `{}` instead of `{..}`
   * Avoid 'Monad of no return` warnings in re-tests.lhs, by using
     Data.Functor.Identity (base >= 4.8.0).
   * Avoid non-canonical `mappend` warnings, by using default
     method (GHC >= 8.4).
   * Avoid redundant case pattern warnings in examples/re-top.lhs
     by moving wired-in choices to the call site.

### CODE REVIEW

**Comment by vdukhovni** [comment]
CI passed on Unix.  Haven't had much luck with github actions on WIndows, so keeping appveyor.yml for now.

**Comment by cdornan** [comment]
Sorry for the delay!

**Comment by vdukhovni** [comment]
Is anything needed from me to get this over the line?

**Comment by cdornan** [comment]
It should be fine -- I am on it now, but will let you know if I need anything. 👍

**Pull request merged**
