### PR TITLE
Add support for 8.2 and 8.4

### PR DESCRIPTION
**Pull request by k-bx**
I'm not sure if I've done everything right, e.g. I've seen something about generated cabal file, so please tell if something else is needed. Otherwise -- builds locally for me on many setups.

### CODE REVIEW

**Comment by k-bx** [comment]
Tests are passing, but still failure. It seems that it comes from:

```
      scan . formatTokens' idFormatTokenREOptions == id: OK (0.07s)
        540 tests completed (but 49 did not meet the condition)
```

**Comment by k-bx** [comment]
`stack test` passes on my Ubuntu machine btw

**Comment by k-bx** [comment]
Also merged-in changes from https://github.com/k-bx/regex/pull/2

**Comment by cdornan** [comment]
Sorted (see #161) &mdash; sorry for the delay.

**Pull request closed without merging**
